name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test on ${{ matrix.os }} with rustc ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - name: Set up a Rust toolchain
      uses: actions-rs/toolchain@v1.0.7
      with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt
    - uses: actions/checkout@v3.2.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_TEST_THREADS=1 cargo test --verbose
    - name: Compile the examples
      run:  cargo build --example sender; cargo build --example receiver
